const ErrorType = {
  SERVER: "INTERNAL_SERVER_ERROR",
  AUTHENTICATION: "UNAUTHENTICATED",
  USER_INPUT: "BAD_USER_INPUT",
  NOT_FOUND: "NOT_FOUND",
  NETWORK: "NETWORK",
  RESPONSE: "RESPONSE_NOT_OK",
  PARSE: "BAD_RESPONSE_FORMAT"
};

const ErrorStatusCodes = {
  USER_INPUT: 400,
  AUTHENTICATION: 403,
  NOT_FOUND: 404,
  SERVER: 500
};

module.exports = {
  ErrorType,
  ErrorStatusCodes
};
